### ISSUE TITLE
TF plugin Json Input async get action

### ISSUE THREAD

**Issue by JernejHabjan** [JernejHabjan/TrumpDefense2020#37]
getnamo/tensorflow-ue4#16 (comment)

getnamo/tensorflow-ue4#37 (comment)

Get action not by running training, but multithreaded JsonInput.

**Comment by getnamo** [comment]
multi-threaded json input support added in https://github.com/getnamo/tensorflow-ue4/releases/tag/0.10.1

**Comment by JernejHabjan** [comment]
Nice - I tried retrieving model actions using json input and it works awesome in async.
Thanks @getnamo
